//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Order
    {
        
 
        public int ProductKey { get; set; }
        public string ProductName { get; set; }
        public decimal Price{ get; set; }
        public int Quantity { get; set; }
        public decimal Discount { get; set; }
       
      }



    }
